### ISSUE TITLE
Dependency on OpenSSL 1.1

### ISSUE THREAD

**Issue by johnalanwoods** [carlobaldassi/liblqr#6]
Hi there,

Many libs depend on liblqr, and currently liblqr depends on OpenSSL 1.0, which has just been deprecated.
This results in broken dependencies for some package managers.

Any possibility we could bump the dependency to a newer version of OpenSSL?

**Comment by sxdjt** [comment]
Bump

**Comment by richardgroves** [comment]
@sxdjt I think it might be due to an only `brew install` of `liblqr` - I had the same problem with `brew doctor` reporting that:

_Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1_

Then when uninstalling openssl@1.1:

**richard@iMac-2020 ~ % brew uninstall openssl@1.1**
_Error: Refusing to uninstall /usr/local/Cellar/openssl@1.1/1.1.1w
because it is required by liblqr, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl@1.1_

But after doing a reinstall of liblqr:

**richard@iMac-2020 ~ % brew reinstall liblqr**
==> Downloading https://ghcr.io/v2/homebrew/core/liblqr/manifests/0.4.2_1-2
################################################################################################################## 100.0%
==> Fetching liblqr
==> Downloading https://ghcr.io/v2/homebrew/core/liblqr/blobs/sha256:03a0e5288bac04044c068ebc27e26cc834f1f2ae483aa7e23663
################################################################################################################## 100.0%
==> Reinstalling liblqr 
==> Pouring liblqr--0.4.2_1.sonoma.bottle.2.tar.gz
🍺  /usr/local/Cellar/liblqr/0.4.2_1: 113 files, 300.3KB
==> Running `brew cleanup liblqr`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).


A new go at uninstalling openssl@1.1:

**richard@iMac-2020 ~ % brew uninstall openssl@1.1**
Uninstalling /usr/local/Cellar/openssl@1.1/1.1.1w... (8,101 files, 18.5MB)

All works fine! My guess is that the homebrew version was a bit out of date, but has been fixed since I last tried removing openssl@1.1. Or a standard brew update wasn't picking up a new version of liblqr - maybe it got re-released with the same version number?

**Comment by sxdjt** [comment]
@richardgroves Solved!  Thanks for that.

**Comment by carlobaldassi** [comment]
Thanks @richardgroves! I'll close this as it seems solved then.
